common: &common
  adapter: postgresql
  username: achievement
  password: underpant5
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *common
  database: achievement_dev

test:
  <<: *common
  database: achievement_test

production:
  <<: *common
  database: achievement_production
